### ISSUE TITLE
Improve output (short array syntax, indentation)

### ISSUE THREAD

**Issue by schmunk42** [hiqdev/composer-config-plugin#10]
It would be nice, if the generated config could use short array syntax, this would make the code much more readable.

Also there could be improvements concerning indentation. If php-cs-fixer does not help, this https://github.com/cmrcx/phptidy is a great tool for formatting PHP code, we're using it in https://github.com/schmunk42/yii2-giiant for years without any problems.

**Comment by hiqsol** [comment]
Good point.

I would not like to generate file and then fix it with some fixer.
I would prefer to generate good file from the beginning.
I've found this lib: https://github.com/Riimu/Kit-PHPEncoder
But I'm looking for alternatives. Have you seen any?

**Comment by schmunk42** [comment]
What about https://github.com/nikic/PHP-Parser?

**Comment by schmunk42** [comment]
Brand new ... https://github.com/symfony/var-exporter.

**Comment by samdark** [comment]
Currently output uses short arrays syntax. @hiqsol this one could be closed.

**Comment by hiqsol** [comment]
I hope it's ok now after implementing [riimu/kit-phpencoder](https://github.com/Riimu/Kit-PHPEncoder)
