### ISSUE TITLE
Question about .env and $_ENV

### ISSUE THREAD

**Issue by pgaultier** [hiqdev/composer-config-plugin#11]
Hello,

I'm using the plugin, but when I create some config with such code : 
```
    'request' => [
        'enableCookieValidation' => false,
        'cookieValidationKey' => $_ENV['YII_COOKIE_VALIDATION_KEY'],
    ],
```
it is compiled as 
```
  array (
    '__class' => 'yii\\web\\Request',
    'enableCookieValidation' => false,
    'cookieValidationKey' => 'qdslkfjlkezhtazehtklezjsqhdflkjqshdfkljsqsfg873dsfqgs32345Y67',
  ),
```

while I was expecting something like this
```
  array (
    '__class' => 'yii\\web\\Request',
    'enableCookieValidation' => false,
    'cookieValidationKey' => $_ENV['YII_COOKIE_VALIDATION_KEY'],
  ),
```
am I doing something wrong ?

**Comment by SilverFire** [comment]
It is an expected behavior. Variables that can be resolved during compilation will be saved as values.

Do you have any problems with it?

**Comment by pgaultier** [comment]
Well, I was reading the generated file and it starts with :

```
$baseDir = dirname(dirname(dirname(__DIR__)));

$_ENV = array_merge((array) require __DIR__ . '/dotenv.php', (array) $_ENV);

require_once $baseDir . '/common/config/defines.php';
require_once $baseDir . '/vendor/yiisoft/yii-core/config/defines.php';
...
```
as the `$_ENV` var is repopulated for each request, I thought the $_ENV could be used.

Anyway, in my case (I'm using flynn for some apps), it is easy to update an environment variable while it's not to re-run `composer du`. Being able to use runtime `$_ENV` would save me some time.

It would be great to be able to tell your plugin if we want to "expand" the `$_ENV` in configs or not.

**Comment by SilverFire** [comment]
@hiqsol

**Comment by hiqsol** [comment]
It can be done but it's not easy.
I hope I'll find time for it later.

**Comment by pgaultier** [comment]
@hiqsol Ok, thank you for your quick answer

**Comment by schmunk42** [comment]
There should be an option like `"evaluate-env": false` to accomplish that.

**Comment by loveorigami** [comment]
May be it is will be usefull
https://github.com/helhum/dotenv-connector
