### ISSUE TITLE
$baseDir in __files, __addition, etc

### ISSUE THREAD

**Issue by loveorigami** [hiqdev/composer-config-plugin#2]
Устанавливаю модули через композер на локалке. На сервере возможности устанивить через composer нет.

Выгружаю вендор на сайт. Ловлю ошибку в файлах __files, __addition и т.д.
Дело в том, что в этих файлах все пути прописаны абсолютно.
например в __addition.php
```
<?php

$baseDir = dirname(dirname(dirname(__DIR__)));

return array (
  'aliases' => 
  array (
    '@yii/bootstrap' => 'X:/domains/site.yii/vendor/yiisoft/yii2-bootstrap',
    '@yii/swiftmailer' => 'X:/domains/site.yii/vendor/yiisoft/yii2-swiftmailer',
  ),
);
``` 
несмотря, на то, что присутствует $baseDir, в выводе массива она никак не используется.

Можно ли содержимое этих файлов сделать, зависящими от $baseDir.
```
return array (
  'aliases' => 
  array (
    '@yii/bootstrap' => $baseDir.'/vendor/yiisoft/yii2-bootstrap',
    '@yii/swiftmailer' =>$baseDir. '/vendor/yiisoft/yii2-swiftmailer',
  ),
);
``` 

Спасибо

**Comment by hiqsol** [comment]
Ща попробую сделать.
Очень интересно почему нельзя композер на сервере запустить?

**Comment by loveorigami** [comment]
) нет доступа по ssh

**Comment by loveorigami** [comment]
может, тогда логичнее сделать, как в самом композере в файле vendor/composer/autoload_files.php и др
```php
// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '2cffec82183ee1cea088009cef9a6fc3' => $vendorDir . '/ezyang/htmlpurifier/library/HTMLPurifier.composer.php',
...........
);

``` 
тогда можно не использовать название папки vendor в пути

**Comment by hiqsol** [comment]
глянь код - писать придётся больше, а функциональность та же

**Comment by loveorigami** [comment]
я понимаю, но это для того, чтобы кто то не нарвался на ошибку, если поменяет название папки vendor.
https://stackoverflow.com/questions/29457345/php-composer-set-vendor-directory

```
add the vendor location to the config section in your composer.json file:
"config": {
    "vendor-dir": "../../path/to/vendors"
}
```

**Comment by hiqsol** [comment]
Вот мой `__addition.php`:

```php
<?php

$baseDir = dirname(dirname(dirname(__DIR__)));

return array (
  'aliases' => 
  array (
    '@yii/twig' => $baseDir . '/vendor/yiisoft/yii2-twig',
  ...
```

не понял почему у тебя не так!
у тебя последняя версия?

**Comment by loveorigami** [comment]
да, 0.2.5
У меня правда, в index.php такой код
```
if (!YII_ENV_PROD) {
    hiqdev\composer\config\Builder::rebuild();
}

$plugin_config = require Builder::path('admin');
```

может в rebuild подставляются абсолютные пути?

**Comment by hiqsol** [comment]
Честно говоря сам не пользуюсь таким принудительным ребилдом, даже на деве.
Дёргаю `composer dump` вручную не так и часто это надо.

Попробуй выпилить и посмотреть пути.

**Comment by loveorigami** [comment]
Убрал rebuild. Удалил \vendor\hiqdev\composer-config-plugin-output.
Сделал composer dump. Получил те же абсолютные пути.

**Comment by loveorigami** [comment]
сам composer у меня - 1.5.2 (stable channel).
в метод writeFile $data не содержит static::BASE_DIR_MARKER, поэтому у меня и не заменяется.
![111](https://user-images.githubusercontent.com/98164/32782163-8c536866-c958-11e7-8c56-f81a123a73d2.jpg)

**Comment by hiqsol** [comment]
а какой BASE_DIR_MARKER?

**Comment by loveorigami** [comment]
Это же константа в билдере
https://github.com/hiqdev/composer-config-plugin/blob/master/src/Builder.php#L50

**Comment by loveorigami** [comment]
Которая, по идее, должна присутствовать в массиве перед ее заменой на $baseDir. А она изначально там отсутствует (см. рис. выше).

**Comment by hiqsol** [comment]
глянь вот отсюда, поймёшь как оно работает:
https://github.com/hiqdev/composer-config-plugin/blob/master/src/Builder.php#L248

что у тебя в `$this->outputDir` ?

я чувствую что-то у тебя странно, но пока не понял что?
Винда?

**Comment by loveorigami** [comment]
да, винда.
 $this->outputDir   = string (62) "X:\domains\gin.yii\vendor\hiqdev\composer-config-plugin-output"

**Comment by loveorigami** [comment]
тут тоже $data с абсолютными путями.
![2017-11-14_17-20-18](https://user-images.githubusercontent.com/98164/32784733-b11f25ce-c960-11e7-9412-1af9668614ad.jpg)

**Comment by hiqsol** [comment]
ну видишь в outputDir слеши в одну сторону, а в массиве в другую
сори, я щас занят, позже подумаю и сделаю чтоб работало

**Comment by loveorigami** [comment]
Тогда нужно нормализовать путь. 
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFileHelper.php#L52
http://www.yiiframework.com/doc-2.0/yii-helpers-basefilehelper.html#normalizePath()-detail

**Comment by hiqsol** [comment]
Добавил нормализацию, попробуй, пожалуйста.
Нет виндовса под рукой проверить.

**Comment by loveorigami** [comment]
Проверил. Все осталось без изменений.

**Comment by hiqsol** [comment]
Вытащил dev версию? (не релизную)

**Comment by loveorigami** [comment]
да

**Comment by loveorigami** [comment]
![2017-11-21_9-48-21](https://user-images.githubusercontent.com/98164/33058542-23e24b64-cea1-11e7-923e-9b91eaf1a3b4.jpg)

Тут видно, что нормализация не сделала правильный путь. Т.к. DIRECTORY_SEPARATOR в винде - \

**Comment by loveorigami** [comment]
Вот тут, видимо, ошибка.
https://github.com/hiqdev/composer-config-plugin/blob/master/src/Builder.php#L293

Опять же, из-за того, что DS в винде = ```\```.

Сделал так
```php
    public static function normalizePath($path, $ds = DIRECTORY_SEPARATOR)
    {
        return rtrim(strtr($path, '\/', '/'), $ds); 
    }

    protected static function substitutePath($path, $dir, $alias)
    {
        $skippable = 0 === strncmp($path, '?', 1) ? '?' : '';
        if ($skippable) {
            $path = substr($path, 1);
        }

       // тут заменил DIRECTORY_SEPARATOR на '/'
        $result = (substr($path, 0, strlen($dir) + 1) === $dir . '/') ? $alias . substr($path, strlen($dir)) : $path;

        return $skippable . $result;
    }
```
И все файлы сформировались правильно

**Comment by hiqsol** [comment]
Попробуй, пожалуйста, с самым последним коммитом.
По прежнему винды под рукой нет.

**Comment by loveorigami** [comment]
Спасибо. Вроде бы все работает правильно.
