### ISSUE TITLE
Dotenv 3 support

### ISSUE THREAD

**Issue by loveorigami** [hiqdev/composer-config-plugin#22]
In new realise Dotenv need to constructor class Loader.
Now I have error

![2019-02-02_15-19-29](https://user-images.githubusercontent.com/98164/52164173-515b5700-26fe-11e9-9466-00bdeebd11dd.jpg)

**Comment by hiqsol** [comment]
It was implemented in https://github.com/hiqdev/composer-config-plugin/commit/597227a727f51aeb36f70837039a8358714a1aa5
