### ISSUE TITLE
Builder::rebuild() create bad config

### ISSUE THREAD

**Issue by loveorigami** [hiqdev/composer-config-plugin#23]
I am create action for rebuild config from cli
 ```php
namespace console\controllers;

use hiqdev\composer\config\Builder;
use yii\console\Controller;

class ConfigController extends Controller
{
    /**
     * Rebuild config
     */
    public function actionDu(): void
    {
        Builder::rebuild();
        $this->stdout('> ok !' . PHP_EOL);
    }
}
```

Next run command ```yii config/du``` and my appliacation is not worked.
I am run command ```composer du``` - all works fine.

Next I compare two configs (cli and composer). They have many differences.

Some of them

![01](https://user-images.githubusercontent.com/98164/52997839-b15a3900-3432-11e9-8426-3bf825591801.jpg)

![02](https://user-images.githubusercontent.com/98164/52997850-b7501a00-3432-11e9-83cc-d3e7d98f8e10.jpg)

![03](https://user-images.githubusercontent.com/98164/52998009-35acbc00-3433-11e9-9e28-c2769da60798.jpg)

and more...

**Comment by loveorigami** [comment]
My config

![04](https://user-images.githubusercontent.com/98164/52998482-70fbba80-3434-11e9-9e34-b0de8028bd86.jpg)

I think - not loaded params from env file.

**Comment by loveorigami** [comment]
Next problems with **$ENV['DB_DSN']** and **getenv('DB_DSN')**

![05](https://user-images.githubusercontent.com/98164/53000167-cf2a9c80-3438-11e9-9f16-b5199979e251.jpg)

![6](https://user-images.githubusercontent.com/98164/53000225-ef5a5b80-3438-11e9-9302-d34bd8ee0370.jpg)

**Comment by loveorigami** [comment]
I think, it will be fixed, if will do #11

**Comment by Spell6inder** [comment]
I also have problems with `Builder::rebuild()`
For example in my file 
```php
// ...
require_once hiqdev\composer\config\Builder::path('defines');
if (YII_ENV_DEV) {
    // my trick
    $_ENV = array_diff_assoc($_ENV, (array) require \hiqdev\composer\config\Builder::path('dotenv'));
    //
    hiqdev\composer\config\Builder::rebuild();
}
// ...
```
On `EnvReader::readRaw($path)` we have `return array_diff_assoc($newenvs, $oldenvs)` but `$oldenvs` (`$_ENV`) already populated. As result empty array returned.
In addition, I think my trick can help the author until the problem is fixed.

**Comment by loveorigami** [comment]
After update to last version my problem is not fixed, but have correct $_ENV

![2019-10-14_13-04-46](https://user-images.githubusercontent.com/98164/66743889-a487cb00-ee83-11e9-93b9-c98245b4213f.jpg)
