### ISSUE TITLE
Line separator problems.

### ISSUE THREAD

**Issue by skeeks-semenov** [hiqdev/composer-config-plugin#24]
If my config file is, and I use the row separator CRLF (windows \r\n)
```
<?php
return [
    'on beforeRequest' => function ($event) {
        \Yii::setAlias('template', '@app/views');
    },
];
```

When I upload a server to Linux, and I write the command composer du, a notice level error occurs. In file Helper public static function dumpClosure(Closure $closure)

Because $lines = file($fun->getFileName()); - return one line.

To solve the problem, I suggest using ini_set ("auto_detect_line_endings", true);
You can call directly in this function, but it can be better like something else.

**Comment by hiqsol** [comment]
This package is deprecated in favour of https://github.com/yiisoft/composer-config-plugin
