### ISSUE TITLE
Question about namespace naming.

### ISSUE THREAD

**Issue by razonyang** [hiqdev/composer-config-plugin#29]
This package is becoming a hard dependency of Yii 3.0 packages, such as yii-console.

Since the Yii 3.0 package's namespace was changed to PascalCase pattern, will this package's namespace follows that pattern in the next release(v1)?

It is not a *real* issue, I am sorry if it bothers you.

**Comment by hiqsol** [comment]
Actually, I like the old style more :) But I think we'll follow this change later.
