### ISSUE TITLE
Notice: Array to string conversion in vendor/hiqdev/composer-config-plugin/src/readers/EnvReader.php on line 34

### ISSUE THREAD

**Issue by thenotsoft** [hiqdev/composer-config-plugin#34]
```
$oldenvs = $_ENV;
...
'argv'=> Array
        (
        )
```

array_diff_assoc обрабатывает только одно измерение, отсюда и ошибка

**Comment by samdark** [comment]
Как воспроизвести?

**Comment by thenotsoft** [comment]
Любой ключ который содержит array вместо string в массиве $_ENV приведет к этой ошибке, в моем случаее `'argv' => array()`

**Comment by hiqsol** [comment]
переделал вообще по другому, должно быть норм сейчас
