### ISSUE TITLE
PHP Warning:  dirname(): Invalid argument, levels must be >= 1

### ISSUE THREAD

**Issue by terabytesoftw** [hiqdev/composer-config-plugin#35]
```
\vendor\hiqdev\composer-config-plugin-output\defines.php on line 3
\vendor\hiqdev\composer-config-plugin-output\dotenv.php on line 3
```

Thks,

**Comment by hiqsol** [comment]
Should be fixed with this commit:

https://github.com/hiqdev/composer-config-plugin/commit/7e7b36e8d62f92a093a05057d32cea65266c8e8c

Could you check it please at your setup.

**Comment by terabytesoftw** [comment]
Thanks for solving the truth that this plugin with yii2 works great.

Thks,
