### ISSUE TITLE
Suggest an array in aliases.php

### ISSUE THREAD

**Issue by kids-return** [hiqdev/composer-config-plugin#37]
vendor/composer/autoload_psr4.php
```php
return [
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
];
```
aliases.php
```php
return [
        '@Psr/Http/Message' => $baseDir . '/vendor/psr/http-factory/src'
];
```
lost `$vendorDir . '/psr/http-factory/src'`
Loss of this directory can cause confusion in use.
May cause unknown bugs when using `aliases.php`

This might be better
```php
return [
        '@Psr/Http/Message' => array($baseDir . '/vendor/psr/http-factory/src', $baseDir . '/vendor/psr/http-message/src'),
];
```

**Comment by kids-return** [comment]
I think it should be fixed here and then compatible in `Yii 3.0`

**Comment by hiqsol** [comment]
Yii doesn't support multi aliases.
It is not difficult to add support to this library.

**Comment by kids-return** [comment]
In fact, this plugin produced results that did not match expectations.
I don't think this plugin will only be applied to Yii.
Here's how to fix `array[0]` when applied to Yii?
Then if Yii supports it, you only need to fix it on Yii over there.
