### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by ncou** [hiqdev/composer-config-plugin#43]
Hi,

Nice piece of code. I think i have spotted a typoe in the readme file :

`You can see the list of configs and files that plugin has detected and uses to build configs. It is located in vendor/hiqdev/composer-config-plugin/output/__files.php`

It should be **'composer-config-plugin-output'** and not 'composer-config-plugin/output'

NB : I think you should also add a check for illegal characters used in the filename for the config-plugin parameter, because if you use a name like this (using a '/' character) :

`"config-plugin": {
        "foo/bar": [xxxxx`

This will create a folder.

**Comment by SilverFire** [comment]
Hello, @ncou.
Thank you for pointing it out!

> It should be **'composer-config-plugin-output'** and not 'composer-config-plugin/output'

Fixed


> NB : I think you should also add a check for illegal characters used in the filename for the config-plugin parameter, because if you use a name like this (using a '/' character) :

Hmm... Need do discuss it with @hiqsol

**Comment by hiqsol** [comment]
> This will create a folder.

Why is it a problem? I think it could be used on some purpose.
