### ISSUE TITLE
why do you use '\' for php functions?

### ISSUE THREAD

**Issue by yurii-github** [hiqdev/composer-config-plugin#44]
why do you use '\\' for php functions?

```
        $args = \func_get_args(); <----- 
        $res = array_shift($args) ?: [];
        foreach ($args as $items) {
            if (!\is_array($items)) { <----------
                continue;
            }
```
https://github.com/hiqdev/composer-config-plugin/blob/master/src/Helper.php#L33

regards

**Comment by SilverFire** [comment]
It's a micro-optimization. You can read more in the following [article](https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/)

**Comment by yurii-github** [comment]
i see, thx.
don't count me salty, but it kinda makes no sense, because

1. there are ton of non fqn functions, even in the same file https://github.com/hiqdev/composer-config-plugin/blob/master/src/Helper.php#L31 , this approach is inconsistent (that's why actually i have asked in 1st place)
2. that micro speed is a myth + it makes no sense in method that must run only once
3. by putting namespace you disable ability to override global function in tests, for example
4. to achieve some speed it's better to decrease number of classes and arrays

regards

p.s.
i'm just bypasser, so don't pay too much attention to my words

**Comment by SilverFire** [comment]
Thanks for sharing your opinion! You know, nowadays I tend to agree with it :)

A few years ago the impact was not significant, but today with PHP 7.3 it should be even less noticeable, especially when we talk about a single call during `composer dump`

> by putting namespace you disable ability to override global function in tests, for example

Yes, that's true, but do you really need to override `is_array` or `func_get_args()`?

**Comment by yurii-github** [comment]
let's say, we don't need https://github.com/php-mock/php-mock
what about situation of list() - https://www.php.net/manual/en/migration70.incompatible.php
> list() no longer assigns variables in reverse order
will you just drop support for PHP5 just because of 1 function

assume array_shift() was bc broken (according to your spec you support up to PHP 8.0), I could simply inject my function like
```
namespace hiqdev\composer\config {
    function array_shift(array &$array) { ... }
}
```
So instead of easily replacing function based on supported language behavior https://www.php.net/manual/en/language.namespaces.fallback.php now I have  to tweak with extension like https://www.php.net/manual/en/function.runkit-function-redefine.php 

p.s.
but of course, probability of such situation is so small as performance gain you get from this "\\", hehe
