### ISSUE TITLE
config-plugin-output-dir doesn't work on Windows

### ISSUE THREAD

**Issue by samdark** [hiqdev/composer-config-plugin#51]
`"config-plugin-output-dir": "runtime/build/config/",` works well when generating files but fails when reading them (adds `vendor` to the path).

Since that's on Windows, it may be an issue alike https://github.com/hiqdev/composer-config-plugin/commit/341d3ade7b2fe466bac2792c3e05a6363a3b7881.

Linux works well.

**Comment by hiqsol** [comment]
I have no windows machine to test.
Could you please make PR? :)

**Comment by samdark** [comment]
Yes. I will check it.
