### ISSUE TITLE
enhancement requiest : option for exclude some package configuration

### ISSUE THREAD

**Issue by jomonkj** [hiqdev/composer-config-plugin#8]
like

```
"extra": {
    "config-plugin": {
        "web": [
            "!vendor/package:$web:config1,config2",
            "src/config/web.php"
        ],
        "other": "config/other.php"
    }
},
```

**Comment by hiqsol** [comment]
Interesting idea but please tell me more why do you need it.
Maybe you are using the plugin wrong...
We are using the plugin for really huge projects and we never needed exclude.

Also I didn't get what your example should exclude exactly.

**Comment by jomonkj** [comment]
I think this option will be required for old projects

**Comment by hiqsol** [comment]
Still we have old projects with lots of legacy and we don't need exclude.

Give me an example please.

**Comment by jomonkj** [comment]
Let me check with other options to fix my config problems.

**Comment by jomonkj** [comment]
here is my problem,
I have a live old project started with the yii2 starter kit (https://github.com/trntv/yii2-starter-kit).
It has its own modules like user, CRM, finance ..etc.
I want to be split them into the standalone module to reuse between projects. 
I faced a problem with migrations, 
all modules have its own migrations and migration namespaces. It will make conflict with the project. here I want to skip particular migrations. 

So, I think this is the solution

**Comment by hiqsol** [comment]
Let's go deeper.

The syntax you propose:

```php
"extra": {
    "config-plugin": {
        "web": [
            "!vendor/package:$web:config1,config2",
            "src/config/web.php"
        ],
    }
},
```

What should it do exactly?
Exclude config1 and config2 items from web config of vendor/package?

**Comment by jomonkj** [comment]
yes, Like
```
"extra": {
    "config-plugin": {
        "console": [
            "!vendor/module-crm:$console:controllerMap.migrate",
            "src/config/console.php"
        ],
    }
},
```
The above composer config will unset `migrate` controller from crm module  console config.
That was my suggestion. 
But now I think, 
Better create an option for `excludeNamespaces` in `migrate` controller
