### ISSUE TITLE
Bug : rebuild() 

### ISSUE THREAD

**Issue by jomonkj** [hiqdev/composer-config-plugin#9]
```
( ! )  Fatal error: Uncaught Error: Call to undefined method  hiqdev\composer\config\Builder::loadFile() in  /app/vendor/hiqdev/composer-config-plugin/src/Builder.php on line 144
--
```

**Comment by loveorigami** [comment]
I have also similar problem. 
I am delete package from vendor and ```composer up``` fix it.
Try

**Comment by hiqsol** [comment]
Not enough tests :(
I'll fix it soon.

**Comment by hiqsol** [comment]
Fixed with latest commit.

Please note that if you want to rebuild config from web entry script you need enough permissions to write to config output dir `vendor/hiqdev/composer-config-plugin-output`.
